language: sh

install:
  - curl -L https://deno.land/x/install/install.sh | sh -s
  - export PATH="$HOME/.deno/bin:$PATH"

script:
  - deno --version
  - deno test --allow-all

cache:
  directories:
    - '$HOME/.deno'